# Stage 1: Build the Java project
FROM maven:3.8.7-openjdk-18-slim AS build
WORKDIR /app
COPY pom.xml .

# Cache the dependencies
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package

# List build files
RUN ls -la /app/target/*

# Stage 2: Create the final image
# bookworm removed openjdk-11-jdk
FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y openjdk-11-jdk && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# -All includes all dependencies
COPY --from=build /app/target/*-All.jar ./app.jar
CMD ["java", "-Dnogui=true", "-jar", "app.jar"]
